feat: initial brew installer
ublue-os/config pull request #235
Opened 2024-03-24 02:10 UTC by gerblesh

## Thank you for contributing to the Universal Blue project!

Please [read the Contributor's Guide](https://universal-blue.org/CONTRIBUTING/) before submitting a pull request.

This PR basically copies the brew installer logic from bluefin:
https://github.com/ublue-os/bluefin/blob/main/usr/etc/profile.d/brew.sh
https://github.com/ublue-os/bluefin/blob/main/Containerfile#L104

only change is using `curl https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | /usr/bin/bash -c` instead of having the install script directly on the image, might be better to directly pull these scripts down when building to keep consistency

2024-03-24 02:49 UTC, gerblesh commented
Brew install/uninstall targets seem to work from my testing. One issue is that the `install-brew` target conflicts with the bluefin `install-brew` so changes might need to be made in upstream bluefin for this to be merged

2024-03-24 20:34 UTC, bsherman reviewed
Why shouldn't we include this file in this PR?

https://github.com/ublue-os/bluefin/blob/main/usr/etc/profile.d/brew.sh

2024-03-24 20:38 UTC, bsherman requested changes
Please add `/usr/etc/profile.d/brew.sh` to the SPEC file.

2024-03-24 21:21 UTC, bsherman commented
RPM fails to build:
```
+ install -Dm755 /tmp/ublue-os/rpmbuild/SOURCES/brew.sh /tmp/ublue-os/rpmbuild/BUILDROOT/ublue-os-just-0.30-1.fc39.x86_64/etc/profile.d/brew.sh
install: cannot stat '/tmp/ublue-os/rpmbuild/SOURCES/brew.sh': No such file or directory
```

2024-03-24 21:35 UTC, bsherman approved these changes
This looks good! Tested locally and seems to do what we expect!

Should probably file an issue in https://github.com/ublue-os/bluefin and/or PR to make changes given the conflict there after this merges, but good stuff.

2024-03-24 21:52 UTC, castrojo approved these changes

2024-03-24 21:54 UTC, merged

2024-03-26 17:17 UTC, citrixscu commented
@bsherman do we also need to add `[dx]/usr/share/fish/vendor_conf.d/brew.fish` to SPEC? Things seem to work fine with bash default shell, but not sure what happens if fish is set to the default login shell.